from .constant_shift_widget import ConstantShiftWidget
from .filter_widget import FilterWidget
from .onset_detection_widget import OnsetDetectionWidget
from .parameter_widget import ParameterWidget
from .peaks_detection_widget import PeaksDetectionWidget
from .rectification_widget import RectificationWidget
from .signal_widget import SignalWidget
from .signal_toolbox import SignalToolboxWidget